Add support for production `kedro viz` backend
quantumblacklabs/kedro-viz pull request #318
Opened 2020-11-26 12:38 UTC by bru5

## Description

Allows development using data from a production backend server.

## Development notes

Enables a production sever running through `kedro viz` to run alongside the dev server through `npm run start`, while forwarding requests to the production API backend.

Changes the default dev server to run on port `4142` and adds a dev server [proxy](https://create-react-app.dev/docs/proxying-api-requests-in-development/) to local production servers on `4141`, which activates only for requests that don't respond on the dev server.

## QA notes

To test run `kedro viz` inside a Kedro project e.g. the [kedro animal example](https://github.com/921kiyo/kedro-animal/) and then run `npm run start` in the Kedro Viz project and visit http://localhost:4142/. You can also visit the production frontend on `4141` at the same time to compare.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

## Legal notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

2020-11-26 13:05 UTC, limdauto approved these changes
💯

2020-11-26 14:01 UTC, richardwestenra requested changes
Looks good, but can you please update the documentation to reflect these changes and document the new behaviour? If you search the codebase for `4141` you'll find many references to the old port, especially in the readme and contrubuting docs, and many of these will need updating.

2020-11-27 12:22 UTC, bru5 commented
@richardwestenra I found out that the command `kedro viz --port 4142` works, so I was able to revert the change such that the existing default behaviour remains the same, the proxy is now for port `4142` instead. Do you think this is worth updating the readme here still or wait until the final workflow is ready?

2020-11-27 16:09 UTC, richardwestenra commented
ok how does this work - does Viz still run in dev on port 4141 as before, but now you can set prod to run on 4142 and dev can access data from prod? Do we need to do anything special to access this data or do we just set it to `data=json` and remove files from `public/api`?

2020-11-27 17:37 UTC, bru5 commented
No changes to existing behaviour, the only difference is when you have no files in `public/api` and request it, rather than just 404 it will then try look for that url over on `4142`, in this case the `kedro viz --port 4142` server if you are running one. Effectively works as if it were on the same server. It's handled by this `react-scripts` feature https://create-react-app.dev/docs/proxying-api-requests-in-development/

2020-11-27 17:45 UTC, richardwestenra approved these changes
Perfect! I'd love a little documentation but no hurry, it's not a blocker. I wonder what's up with Snyk though..

2020-11-30 10:05 UTC, bru5 commented
Sure I think once all parts of the backend workflow are finalised it will make sense to document the process, hopefully that will be soon.

2020-12-01 10:34 UTC, merged